cc_test(
  name = "mylogfilemgrtest",
  size = "small",
  srcs = [
    "logfilemgrtest.cpp",
  ],
  deps = [
    "//3rd/gtest:gtest_main",
    "//2nd/log:mylogfilemgr",
  ],
  copts = [
    "-std=c++17",
  ],
  linkopts = [
    "-std=c++17",
  ],
)
