cc_binary(
  name = "mysvrkit",
  srcs = [
    "main.cpp",
    "server.h",
    "server.cpp",
    "error_code.h",
  ],
  includes = [],
  deps = [
    "//mysvrkit/log:mylog",
  ],
  copts = [
    "-std=c++17",
  ],
  linkopts = [
    "-std=c++17",
  ],
)
